package inf112.project.RoboRally.game;

public enum GameStatus {

    SELECT_CARDS,
    POWER_DOWN,
    EXECUTING_INSTRUCTIONS,
    EXECUTING_GAME_BOARD_OBJECTS,
    FIRING_LASERS,
 //   TOUCH_FLAGS_AND_REPAIR_SITES,?
    FINISHING_UP_THE_TURN,
    THE_END

}
